packages:
  - packages/*
  - services/*
allowBuilds:
  '@reown/appkit': false
  bufferutil: false
  esbuild: true
  keccak: false
  sharp: true
  utf-8-validate: false
onlyBuiltDependencies:
  - esbuild
  - sharp
