// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {MockUSDC} from "../src/MockUSDC.sol";
import {AccumulatorVault} from "../src/AccumulatorVault.sol";
import {KickoffEscrow} from "../src/KickoffEscrow.sol";

/// Differential test: replays random settlement cases generated by the TS
/// engine (scripts/gen-differential.ts → test/fixtures/differential.json)
/// and asserts the Solidity port produces byte-identical payouts, platform
/// cut, and accumulator contribution. This is the proof the two engines are
/// the same math, not just similar math.
contract DifferentialTest is Test {
    using stdJson for string;

    MockUSDC internal usdc;
    AccumulatorVault internal vault;
    KickoffEscrow internal escrow;

    address internal owner = makeAddr("owner");
    address internal relayer = makeAddr("relayer");
    address internal agent = makeAddr("agent");

    uint64 internal constant LOCKS_AT = 1_000_000;

    string internal json;
    uint256 internal nCases;

    function setUp() public {
        vm.warp(1);
        usdc = new MockUSDC();
        vm.startPrank(owner);
        vault = new AccumulatorVault(address(usdc), relayer);
        escrow = new KickoffEscrow(address(usdc), relayer, agent, address(vault));
        vault.registerEscrow(address(escrow), true);
        vm.stopPrank();

        json = vm.readFile("test/fixtures/differential.json");
        // Cases are a fixed-size array written by the generator; count by probing.
        nCases = 0;
        while (vm.keyExistsJson(json, string.concat(".cases[", vm.toString(nCases), "].gamma"))) {
            nCases++;
        }
        assertGt(nCases, 0, "fixture file has cases");
    }

    function test_differentialAgainstTsEngine() public {
        for (uint256 c = 0; c < nCases; c++) {
            string memory base = string.concat(".cases[", vm.toString(c), "]");

            uint256 gamma = json.readUint(string.concat(base, ".gamma"));
            uint256 actualHome = json.readUint(string.concat(base, ".actualHome"));
            uint256 actualAway = json.readUint(string.concat(base, ".actualAway"));
            uint256[] memory stakes = _readUintArray(string.concat(base, ".stakes"));
            uint256[] memory gh = json.readUintArray(string.concat(base, ".guessHome"));
            uint256[] memory ga = json.readUintArray(string.concat(base, ".guessAway"));
            uint256[] memory expected = _readUintArray(string.concat(base, ".expectedPayouts"));
            uint256 expPlatform = _readUintString(string.concat(base, ".expectedPlatformCut"));
            uint256 expAcc = _readUintString(string.concat(base, ".expectedAcc"));
            bool expVoid = json.readBool(string.concat(base, ".expectedVoid"));

            uint256 marketId = _runCase(gamma, stakes, gh, ga, actualHome, actualAway);

            for (uint256 i = 0; i < stakes.length; i++) {
                assertEq(
                    escrow.payoutOf(marketId, _trader(c, i)),
                    expected[i],
                    string.concat("case ", vm.toString(c), " trader ", vm.toString(i))
                );
            }
            (,,,,,, uint128 acc, uint128 platformCut,,) = _summary(marketId);
            if (!expVoid) {
                assertEq(uint256(platformCut), expPlatform, string.concat("case ", vm.toString(c), " platformCut"));
                assertEq(uint256(acc), expAcc, string.concat("case ", vm.toString(c), " acc"));
            }
        }
    }

    function _runCase(
        uint256 gamma,
        uint256[] memory stakes,
        uint256[] memory gh,
        uint256[] memory ga,
        uint256 actualHome,
        uint256 actualAway
    ) internal returns (uint256 marketId) {
        // Fresh clock per case: markets share LOCKS_AT, so rewind before staking.
        vm.warp(1);
        vm.startPrank(agent);
        marketId = escrow.createMarket(
            KickoffEscrow.MarketConfig({
                kind: KickoffEscrow.MarketKind.Scoreline,
                stakeMode: KickoffEscrow.StakeMode.Variable,
                gamma: uint8(gamma),
                takeRateBps: 1000,
                accShareBps: 5000,
                capMultiple: 100,
                maxPositions: 300,
                locksAt: LOCKS_AT,
                minStake: 1e6,
                maxStake: 500e6,
                fixedStake: 0
            })
        );
        escrow.openMarket(marketId);
        vm.stopPrank();

        for (uint256 i = 0; i < stakes.length; i++) {
            address t = _trader(marketId - 1, i); // marketId == caseIdx + 1
            vm.startPrank(t);
            usdc.faucet(stakes[i]);
            usdc.approve(address(escrow), stakes[i]);
            escrow.stake(marketId, uint32(gh[i]), uint32(ga[i]), uint128(stakes[i]));
            vm.stopPrank();
        }

        vm.warp(LOCKS_AT);
        vm.prank(relayer);
        escrow.settle(marketId, uint32(actualHome), uint32(actualAway));
    }

    /// Trader addresses derived from (marketId, index); marketId == case+1
    /// because cases run sequentially on a fresh escrow.
    function _trader(uint256 caseIdx, uint256 i) internal pure returns (address) {
        return address(uint160(uint256(keccak256(abi.encode("diff-trader", caseIdx + 1, i)))));
    }

    // Stakes/payouts are decimal STRINGS in the JSON (JS bigints); parse them.
    function _readUintArray(string memory key) internal view returns (uint256[] memory out) {
        string[] memory raw = json.readStringArray(key);
        out = new uint256[](raw.length);
        for (uint256 i = 0; i < raw.length; i++) {
            out[i] = vm.parseUint(raw[i]);
        }
    }

    function _readUintString(string memory key) internal view returns (uint256) {
        return vm.parseUint(json.readString(key));
    }

    function _summary(uint256 id)
        internal
        view
        returns (
            KickoffEscrow.MarketStatus status,
            uint128 totalPool,
            uint32 actualA,
            uint32 actualB,
            uint128 losersStakeSum,
            uint128 losersDup,
            uint128 acc,
            uint128 platformCut,
            uint128 medianD,
            bool coalitionMode
        )
    {
        KickoffEscrow.MarketConfig memory cfg;
        (status, cfg, totalPool, actualA, actualB, losersStakeSum, acc, platformCut, medianD, coalitionMode) =
            escrow.markets(id);
        losersDup = losersStakeSum;
        cfg;
    }
}
